# Generated by Django 4.1.4 on 2023-04-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="profile_picture",
        ),
    ]
