# Generated by Django 4.1.4 on 2023-04-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_profile", "0002_remove_accountprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountprofile",
            options={
                "verbose_name": "Account Profile",
                "verbose_name_plural": "Account Profiles",
            },
        ),
    ]
